CREATE DATABASE IF NOT EXISTS insumos;
USE insumos;

CREATE TABLE IF NOT EXISTS productos_generales (
    codigo INT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS pedido (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    cantidad VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    empleado VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS productos (
    codigo INT PRIMARY KEY,  -- Código como clave primaria
    nombre VARCHAR(255) NOT NULL,     -- Nombre del producto
    categoria VARCHAR(255) NOT NULL   -- Categoría del producto
);



CREATE TABLE IF NOT EXISTS pedido_cocina (
    id INT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    cantidad VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    empleado VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS productos_cocina (
    codigo INT PRIMARY KEY,  -- Código como clave primaria
    nombre VARCHAR(255) NOT NULL,     -- Nombre del producto
    categoria VARCHAR(255) NOT NULL   -- Categoría del producto
);



CREATE TABLE IF NOT EXISTS empleados (
    id INT AUTO_INCREMENT PRIMARY KEY,
    phone VARCHAR(10) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    area ENUM('barra', 'admin', 'repartidor') NOT NULL
);

INSERT INTO empleados (phone, password, nombre, area) VALUES
('5551234567', 'claveSegura1', 'Juan Pérez', 'admin'),
('5559876543', 'reparto123', 'María González', 'repartidor'),
('5555555555', 'barraFuerte', 'Carlos López', 'barra'),
('5553334444', 'adminBoss', 'Laura Méndez', 'admin'),
('5556667777', 'deliveryGo', 'Pedro Ramírez', 'repartidor'),
('5552223333', 'mojitosBest', 'Sofía Torres', 'barra'),
('5558889999', 'seguroAdmin', 'Ana Villalobos', 'admin'),
('5557776666', 'speedyMoto', 'Diego Herrera', 'repartidor'),
('5554445555', 'mixDrinks', 'Elena Rojas', 'barra'),
('5551112222', 'adminPower', 'Fernando Castro', 'admin');


-- Insertar productos para una cafetería en productos_generales
INSERT INTO productos_generales (codigo, nombre, categoria) VALUES
(539, 'Zanahoria', 'Frutas y Verduras'),
(584, 'Yogurt Natural', 'Lacteos'),
(642, 'Vino California', 'Abarrotes'),
(862, 'Vino Blanco', 'Abarrotes'),
(873, 'Vinagre', 'Abarrotes'),
(692, 'Vaso Cristal 7oz', 'Desechables'),
(699, 'Vaso Cristal 16oz', 'Desechables'),
(688, 'Vaso Bamboo 8oz', 'Desechables'),
(689, 'Vaso Bamboo 12oz', 'Desechables'),
(700, 'Vaso Bamboo 16oz', 'Desechables'),
(311, 'Vaso 4oz', 'Desechables'),
(925, 'Vaso 2oz', 'Desechables'),
(905, 'Vaso 12oz', 'Desechables'),
(637, 'Valentina sobre 8gr', 'Abarrotes'),
(829, 'Vainilla Sayes 1L', 'Caliente'),
(789, 'Tortillas', 'Panaderia y pasteleria'),
(538, 'Tomate Verde', 'Frutas y Verduras'),
(550, 'Tomate cherry cajita', 'Frutas y Verduras'),
(556, 'Tocino', 'Carne embutido y mariscos'),
(567, 'Tocineta', 'Carne embutido y mariscos'),
(747, 'Tizana strawberry Kiwi 500g', 'Cafe endulzantes y saborizantes'),
(778, 'Tizana Recuerdame 500 gramos', 'Cafe endulzantes y saborizantes'),
(746, 'Tizana Raiz 500g', 'Cafe endulzantes y saborizantes'),
(739, 'Tizana Ponche de Guayaba 500g', 'Cafe endulzantes y saborizantes'),
(740, 'Tizana Pina Colada 500g', 'Cafe endulzantes y saborizantes'),
(736, 'Tizana Oms Garden 500g', 'Cafe endulzantes y saborizantes'),
(737, 'Tizana Mumbai 500g', 'Cafe endulzantes y saborizantes'),
(738, 'Tizana Manzana-Arandano 500g', 'Cafe endulzantes y saborizantes'),
(745, 'Tizana Hakuna Matata 500g', 'Cafe endulzantes y saborizantes'),
(741, 'Tizana Goji Berry 500g', 'Cafe endulzantes y saborizantes'),
(744, 'Tizana Dulce Amanecer 500g', 'Cafe endulzantes y saborizantes'),
(742, 'Tizana Besos Rosas 500g', 'Cafe endulzantes y saborizantes'),
(743, 'Tizana Atardecer 500g', 'Cafe endulzantes y saborizantes'),
(677, 'Tenedores Desechables Jumbo', 'Desechables'),
(605, 'Teleras', 'Panaderia y pasteleria'),
(970, 'Te verde en sobres', 'Barra-Bebidas - Caliente'),
(626, 'Te manzanilla sobres', 'Abarrotes'),
(733, 'Te Manzana-Canela en sobres', 'Cafe endulzantes y saborizantes'),
(729, 'Te Jamaica en sobres', 'Cafe endulzantes y saborizantes'),
(730, 'Te Hierbabuena en sobres', 'Cafe endulzantes y saborizantes'),
(817, 'Te de limon en sobres', 'Cafe endulzantes y saborizantes'),
(731, 'Te de Canela en sobres', 'Cafe endulzantes y saborizantes'),
(818, 'Te de 7 en sobres', 'Cafe endulzantes y saborizantes'),
(886, 'Te caja varios sabores', 'Cafe endulzantes y saborizantes'),
(554, 'Tasajo', 'Carne embutidos y mariscos'),
(890, 'Tapas para jugo 7 oz', 'Desechables'),
(870, 'Tapas contenedores consome 1/2', 'Desechables'),
(927, 'Tapa vaso 2 oz', 'Abarrotes'),
(686, 'Tapa Negra 8oz', 'Desechables'),
(800, 'Tapa negra 12/16 oz 50 piezas', 'Desechables'),
(790, 'Tapa domo de vaso Cristal', 'Desechables'),
(308, 'TAPA 4 Oz', 'Desechables'),
(904, 'Tapa 1 oz 100 piezas', 'Desechables'),
(932, 'Tajin', 'Abarrotes'),
(639, 'Stevia', 'Cafe endulzantes y saborizantes'),
(844, 'Splenda endulzante sobres', 'Cafe endulzantes y saborizantes'),
(906, 'Servitoallas para secar verduras', 'Abarrotes'),
(691, 'Servitoallas', 'Desechables'),
(823, 'Servilletas paquete grande', 'Desechables'),
(989, 'Semillas de calabaza', 'Abarrotes'),
(592, 'Semilla de girasol 1/4', 'Chiles secos, semillas, harinas y pastas'),
(663, 'Sanitas 1 paquete', 'Productos de limpieza'),
(811, 'Sandia', 'Frutas y verduras'),
(987, 'Salsa magui', 'Abarrotes'),
(892, 'Salsa inglesa', 'Abarrotes'),
(861, 'Salsa hunts tipo bolonesa', 'Abarrotes'),
(850, 'Salsa Hunts BBQ 620g', 'Abarrotes'),
(726, 'Salsa de Chocolate Blanco', 'Cafe endulzantes y saborizantes'),
(496, 'Salsa de chocolate', 'Cafe endulzantes y saborizantes'),
(672, 'Salsa De Caramelo', 'Cafe endulzantes y saborizantes'),
(820, 'SALSA CATSUP 450 G', 'Material de uso'),
(986, 'Salsa bufalo', 'Abarrotes'),
(564, 'Salchichas En Paquete', 'Carne embutidos y mariscos'),
(952, 'Sal de grano de 1kg', 'Cocina-Produccion - A cualquier hora'),
(926, 'Sal con ajo', 'Abarrotes'),
(649, 'Sal blanca de 1kg', 'Abarrotes'),
(822, 'Sal sol / sal fina', 'Material de uso'),
(667, 'Rollo papel higienico', 'Productos de limpieza'),
(525, 'Rollo de Espinacas', 'Frutas y verduras'),
(524, 'Rollo de Epazote', 'Frutas y verduras'),
(522, 'Rollo de Cilantro', 'Frutas y verduras'),
(994, 'Retazo', 'Carne embutidos y mariscos'),
(1032, 'Red para cabello', 'Material de uso'),
(535, 'Ramo de Perejil', 'Frutas y verduras'),
(574, 'Quesos De Aro', 'Lacteos'),
(585, 'Queso parmesano rayado', 'Lacteos'),
(922, 'Queso para nachos', 'Abarrotes'),
(576, 'Queso Panela 400 Grs', 'Lacteos'),
(578, 'Queso manchego rallado', 'Lacteos'),
(851, 'Queso gouda el buen pastor de 500g', 'Cocina-Produccion - Comidas'),
(620, 'Queso crema la cima cubeta 4kg', 'Panaderia y pasteleria'),
(860, 'Queso americano/amarillo paquetes', 'Material de uso'),
(988, 'Quesillo 1Kg', 'Lacteos'),
(773, 'Pulpa de Zarzamora', 'Cafe endulzantes y saborizantes'),
(787, 'Pulpa de Mixies berries', 'Cafe endulzantes y saborizantes'),
(786, 'Pulpa de Maracuya', 'Cafe endulzantes y saborizantes'),
(772, 'Pulpa de Mango', 'Cafe endulzantes y saborizantes'),
(774, 'Pulpa de Kiwi', 'Cafe endulzantes y saborizantes'),
(898, 'Pulpa de fresa', 'Cafe endulzantes y saborizantes'),
(762, 'Pulpa de concentrado de piña coco', 'Material de uso'),
(701, 'Porta Vasos pieza', 'Desechables'),
(693, 'Popotes Estuchados 26cm', 'Desechables'),
(728, 'Polvo Frappe Base Leche', 'Café, endulzantes y saborizantes'),
(727, 'Polvo Frappe Base Agua', 'Café, endulzantes y saborizantes'),
(991, 'Polvo flan', 'Café, endulzantes y saborizantes'),
(798, 'Pollo surtido', 'Carne, embutidos y mariscos'),
(859, 'Platos desechables para fruta n.2', 'Desechables'),
(537, 'Plátano tabasco', 'Frutas y verduras'),
(936, 'Plastico aderhente 100m', 'Otros - Otros'),
(660, 'Pinol', 'Productos de limpieza'),
(828, 'Piña en rebanadas en almibar', 'Cocina-Producción - Comidas'),
(546, 'Piña', 'Frutas y verduras'),
(635, 'Pimienta molida con sal', 'Abarrotes'),
(893, 'Piloncillo por pieza', 'Abarrotes'),
(563, 'Pepperoni', 'Carne, embutidos y mariscos'),
(795, 'Pepino', 'Frutas y verduras'),
(799, 'Peñafiel mineral paquete de 6', 'Bebidas no alcohólicas'),
(963, 'Peñafiel mineral grande', 'Abarrotes'),
(557, 'Pechuga De Pollo Entera', 'Carne, embutidos y mariscos'),
(559, 'Pechuga De Pollo Aplanada', 'Carne, embutidos y mariscos'),
(230, 'PASTILLA PARA BAÑO PATO 4PZ', 'Material de uso'),
(819, 'Pasta tornillo rotini 1kg', 'Chiles secos, semillas, harinas y pastas'),
(877, 'Pasta para lasaña', 'Abarrotes'),
(821, 'Pasta fideo para sopa', 'Chiles secos, semillas, harinas y pastas'),
(977, 'Pasta espaguetti', 'Material de uso'),
(664, 'Papel higiénico junior por pieza', 'Productos de limpieza'),
(900, 'Papel corrugado paquete 10 pliegos', 'Otros'),
(534, 'Papaya', 'Frutas y verduras'),
(911, 'Papas francesas en porciones', 'Abarrotes'),
(624, 'Papas a la francesa en bolsa kg', 'Abarrotes'),
(793, 'Papa blanca', 'Frutas y verduras'),
(985, 'Pan para hamburguesa bimbollo', 'Abarrotes'),
(609, 'Pan molido', 'Panadería y pastelería'),
(601, 'Pan integral de caja', 'Panadería y pastelería'),
(606, 'Pan dulce', 'Panadería y pastelería'),
(600, 'Pan de hamburguesa wonder 8 pzas', 'Panadería y pastelería'),
(636, 'Palillos', 'Abarrotes'),
(533, 'Orégano', 'Frutas y verduras'),
(930, 'Nutela / crema de avellanas', 'Abarrotes'),
(869, 'Nuez picada', 'Chiles secos, semillas, harinas y pastas'),
(868, 'Nuez entera', 'Chiles secos, semillas, harinas y pastas'),
(542, 'Nopales limpios', 'Frutas y verduras'),
(981, 'Naranja por kilo', 'Frutas y verduras'),
(858, 'Mostaza', 'Abarrotes'),
(655, 'Mole', 'Abarrotes'),
(857, 'Miel de maple', 'Café, endulzantes y saborizantes'),
(1023, 'Microfibra', 'Otros - Otros'),
(652, 'Microdyn 100ml', 'Abarrotes'),
(628, 'Mermelada grande', 'Abarrotes'),
(618, 'Chocolate Turín amargo 100g', 'Panadería y pastelería'),
(750, 'Chocolate Oaxacanita', 'Café, endulzantes y saborizantes'),
(889, 'Chocolate líquido', 'Café, endulzantes y saborizantes'),
(990, 'Chispas de colores', 'Abarrotes'),
(617, 'Chispas de chocolate', 'Panadería y pastelería'),
(907, 'Chiles en vinagre en rajas', 'Abarrotes'),
(801, 'Chile/ pimiento morrón', 'Frutas y verduras'),
(521, 'Chile serrano', 'Frutas y verduras'),
(853, 'Chile jalapeño', 'Frutas y verduras'),
(527, 'Chile habanero', 'Frutas y verduras'),
(999, 'Chile guajillo', 'Frutas y verduras'),
(899, 'Chile costeño amarillo de 150g', 'Cocina-Producción - Comidas'),
(650, 'Chile chipotle lata', 'Abarrotes'),
(101, 'Chicharrón De Puerco', 'Carne, embutidos y mariscos'),
(796, 'Chayote', 'Frutas y verduras'),
(520, 'Champiñones', 'Frutas y verduras'),
(645, 'Chamoy 1l', 'Abarrotes'),
(855, 'Cereza en almibar', 'Frutas y verduras'),
(813, 'Cecina', 'Carne, embutidos y mariscos'),
(519, 'Cebolla morada', 'Frutas y verduras'),
(803, 'Cebolla Cambray', 'Frutas y verduras'),
(000, 'Cebolla Blanca', 'Frutas y verduras'),
(640, 'Catsup en sobrecitos', 'Abarrotes'),
(633, 'Casilleros de huevo', 'Abarrotes'),
(897, 'Carne para hervir', 'Carne, embutidos y mariscos'),
(832, 'Carne para freir', 'Carne, embutidos y mariscos'),
(562, 'Carne Molida Mixta', 'Material de uso'),
(561, 'Carne Molida De Res', 'Carne, embutidos y mariscos'),
(560, 'Carne Molida De Pollo', 'Carne, embutidos y mariscos'),
(555, 'Carne Enchilada', 'Carne, embutidos y mariscos'),
(848, 'Carnation en polvo de 460g', 'Barra-Bebidas - Fri@s'),
(613, 'Capacillo para postres', 'Panadería y pastelería'),
(615, 'Canela molida/ en polvo', 'Panadería y pastelería'),
(967, 'Canela en trozos', 'Abarrotes'),
(506, 'Camarón', 'Carne, embutidos y mariscos'),
(517, 'Calabaza', 'Frutas y verduras'),
(849, 'Cajeta', 'Barra-Bebidas - Caliente'),
(1039, 'Cafés fino Cuatepec tueste medio', 'Cocina-Producción - A cualquier hora'),
(1057, 'Cafe Especial tueste medio Cuatepec', 'Barra-Bebidas - Caliente'),
(1012, 'Cafe de la casa tueste medio', 'Barra-Bebidas - Caliente'),
(495, 'Café de la casa 90 10', 'Café, endulzantes y saborizantes'),
(494, 'Café de la casa 70 30 1 KG', 'Café, endulzantes y saborizantes'),
(791, 'Bulto de naranja', 'Frutas y verduras'),
(831, 'Brocoli', 'Frutas y verduras'),
(683, 'Bolsas Para Porcionar', 'Desechables'),
(682, 'Bolsas De Papel No.3', 'Desechables'),
(879, 'Bolsas de papel #6', 'Abarrotes'),
(783, 'Bolsas 1kg 90X120', 'Desechables'),
(784, 'Bolsas 1kg 60X90', 'Desechables'),
(634, 'Bolsa de hielos', 'Abarrotes'),
(703, 'Bolsa 50x60 grande con asa', 'Desechables'),
(975, 'Bolsa 40x50 mediana con asa', 'Material de uso'),
(702, 'Bolsa 35x40 chica con asa', 'Desechables'),
(541, 'Blueberry 400g', 'Frutas y verduras'),
(552, 'Bistec de res', 'Carne, embutidos y mariscos'),
(933, 'Banderillas de tamarindo', 'Abarrotes'),
(602, 'Baguettes grandes', 'Panadería y pastelería'),
(920, 'Azucar refinado en sobres', 'Material de uso'),
(843, 'Azúcar mascabado en sobresitos', 'Café, endulzantes y saborizantes'),
(816, 'Azucar mascabado en kilo', 'Café, endulzantes y saborizantes'),
(871, 'Azúcar glass', 'Café, endulzantes y saborizantes'),
(643, 'Azúcar estándar de 1kg', 'Abarrotes'),
(827, 'Avena a granel de un 1kg', 'Abarrotes'),
(841, 'Atún en lata', 'Carne, embutidos y mariscos'),
(588, 'Arroz de kilo', 'Abarrotes'),
(551, 'Arrachera', 'Carne, embutidos y mariscos'),
(593, 'Arándanos', 'Chiles secos, semillas, harinas y pastas'),
(545, 'Apio', 'Frutas y verduras'),
(684, 'Aluminio 100 Metros', 'Desechables'),
(565, 'Alitas de pollo', 'Carne, embutidos y mariscos'),
(513, 'Ajo de cabeza grande', 'Frutas y verduras'),
(228, 'Ajax multiuso', 'Material de uso'),
(512, 'Aguacate', 'Frutas y verduras'),
(882, 'Agitadores', 'Abarrotes'),
(646, 'Aderezo ranch', 'Abarrotes'),
(1017, 'Aderezo chipotle', 'Abarrotes'),
(854, 'Aderezo césar', 'Abarrotes'),
(845, 'Achiote', 'Chiles secos, semillas, harinas y pastas'),
(929, 'Aceitunas', 'Abarrotes'),
(864, 'Aceite en aerosol', 'Abarrotes'),
(863, 'Aceite de oliva', 'Abarrotes'),
(779, 'Aceite 123', 'Abarrotes'),
(924, 'Valentina 1 LT', 'Abarrotes');

